/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cplusplus */

#ifndef _Included_cplusplus
#define _Included_cplusplus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cplusplus
 * Method:    print
 * Signature: ()Ljava/lang/String;
 */

JNIEXPORT jstring JNICALL Java_cplusplus_x
  (JNIEnv *, jclass, jstring);

JNIEXPORT jstring JNICALL Java_cplusplus_a
	(JNIEnv *, jclass);

/*
 * Class:     cplusplus
 * Method:    ReadMemoryAddr
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cplusplus_b
  (JNIEnv *, jclass, jint, jint);
  
  JNIEXPORT jstring JNICALL Java_cplusplus_c
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT jdouble JNICALL Java_cplusplus_d
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT jstring JNICALL Java_cplusplus_e
  (JNIEnv *, jclass, jint, jint);
/*
*/
JNIEXPORT jstring JNICALL Java_cplusplus_f
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_cplusplus_g
  (JNIEnv *, jclass);
JNIEXPORT jint JNICALL Java_cplusplus_h(JNIEnv *env, jclass obj, jstring mod);

JNIEXPORT jstring JNICALL Java_cplusplus_i(JNIEnv *env, jclass obj);

JNIEXPORT jstring JNICALL Java_cplusplus_j(JNIEnv *, jclass);

JNIEXPORT bool JNICALL Java_cplusplus_k(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_cplusplus_l(JNIEnv*, jclass, jstring);

JNIEXPORT jstring JNICALL Java_cplusplus_m(JNIEnv*, jclass);

JNIEXPORT void JNICALL Java_cplusplus_n(JNIEnv*, jclass);

JNIEXPORT int JNICALL Java_cplusplus_o(JNIEnv*, jclass, jstring, jstring);

JNIEXPORT jstring JNICALL Java_cplusplus_p(JNIEnv*, jclass, jstring, jstring, jint);

JNIEXPORT jstring JNICALL Java_cplusplus_q(JNIEnv*, jclass, jstring);


//JNIEXPORT jint JNICALL Java_cplusplus_GetSecretDlls(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
